import type { Express } from 'express';
import { GoogleGenAI } from '@google/genai';

type Db = { settings?: any; reviews?: any[]; waiters?: any[]; rewards?: any[] };
const overall=(r:any)=>{const v=[r?.ratings?.service,r?.ratings?.ambiance,r?.ratings?.products,r?.ratings?.waitTime].map(Number).filter(x=>Number.isFinite(x)&&x>0);return v.length?v.reduce((a,b)=>a+b,0)/v.length:0};
function select(reviews:any[],period:string){const now=new Date();if(period==='all')return{current:reviews,previous:[],label:'todo o período'};if(period==='today'){const s=new Date(now.getFullYear(),now.getMonth(),now.getDate()),p=new Date(s);p.setDate(p.getDate()-1);return{current:reviews.filter(r=>new Date(r.createdAt)>=s),previous:reviews.filter(r=>{const d=new Date(r.createdAt);return d>=p&&d<s}),label:'hoje'}}const days=period==='7d'?7:30,s=new Date(now),p=new Date(now);s.setDate(s.getDate()-days);p.setDate(p.getDate()-days*2);return{current:reviews.filter(r=>new Date(r.createdAt)>=s),previous:reviews.filter(r=>{const d=new Date(r.createdAt);return d>=p&&d<s}),label:`últimos ${days} dias`}}
function compact(rs:any[]){return rs.slice(0,350).map(r=>({createdAt:r.createdAt,tableNumber:r.tableNumber,ratings:r.ratings,quickTags:Array.isArray(r.quickTags)?r.quickTags.slice(0,12):[],criticism:String(r.criticism||'').slice(0,500),suggestion:String(r.suggestion||'').slice(0,500),waiterName:r.waiterName||undefined,waiterRating:r.waiterRating||undefined,waiterCompliments:r.waiterCompliments||(r.waiterCompliment?[r.waiterCompliment]:[]),rewardTitle:r.rewardTitle||undefined,rewardClaimed:Boolean(r.rewardClaimed)}))}
function stats(rs:any[]){const a:any={};for(const k of ['service','ambiance','products','waitTime']){const v=rs.map(r=>Number(r?.ratings?.[k])).filter(x=>Number.isFinite(x)&&x>0);a[k]=v.length?Number((v.reduce((x,y)=>x+y,0)/v.length).toFixed(2)):null}const ov=rs.map(overall).filter(x=>x>0);return{total:rs.length,overall:ov.length?Number((ov.reduce((x,y)=>x+y,0)/ov.length).toFixed(2)):null,...a,criticisms:rs.filter(r=>String(r.criticism||'').trim()).length,suggestions:rs.filter(r=>String(r.suggestion||'').trim()).length,vouchersIssued:rs.filter(r=>r.rewardCode).length,vouchersClaimed:rs.filter(r=>r.rewardClaimed).length}}
function client(){const key=String(process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY||'').trim();return key?new GoogleGenAI({apiKey:key}):null}
function isPro(db:Db){const raw=db?.settings?.plan ?? db?.settings?.subscriptionPlan ?? db?.settings?.currentPlan ?? db?.settings?.tier ?? db?.settings?.subscription?.plan ?? '';const plan=String(raw).trim().toLowerCase();return plan==='pro'||plan==='profissional'}
function requirePro(db:Db,res:any){if(isPro(db))return true;res.status(403).json({error:'Recurso exclusivo do plano Pro.',code:'PRO_REQUIRED'});return false}
function json(raw:string){return JSON.parse(String(raw||'').replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/,'').trim())}

export function registerAiRoutes(app: Express, getDb:()=>Db, getCompanyId:()=>string){
  app.get('/api/ai/entitlement',(_req,res)=>{const db=getDb();return res.json({pro:isPro(db)});});
  app.post('/api/ai/report',async(req,res)=>{try{const db=getDb();if(!requirePro(db,res))return;const ai=client();if(!ai)return res.status(503).json({error:'Configure GEMINI_API_KEY no Render para ativar os relatórios de IA.'});const period=['today','7d','30d','all'].includes(String(req.body?.period))?String(req.body.period):'30d';const{current,previous,label}=select(db.reviews||[],period);if(!current.length)return res.json({success:true,report:{generatedAt:new Date().toISOString(),period:label,summary:'Ainda não há avaliações no período selecionado.',status:'sem_dados',confidenceNote:'Sem dados suficientes para análise.',highlights:[],alerts:[],evolution:[],themes:[],productInsights:[],waiterInsights:[],criticalHours:[],recommendations:[],weeklyPriority:null,finalPhrase:'Aguardando novas avaliações para gerar uma análise confiável.'}});
  const payload={company:db.settings?.name||getCompanyId(),period:label,currentStats:stats(current),previousStats:stats(previous),currentReviews:compact(current),previousReviews:compact(previous),activeWaiters:(db.waiters||[]).filter((w:any)=>w.active).map((w:any)=>({name:w.name,role:w.role}))};
  const prompt=`Você é o analista de experiência do cliente do sistema Avalia e Ganha. Analise SOMENTE os dados fornecidos. Nunca invente números, motivos, produtos, comentários, horários ou tendências. Pequenas variações não são tendência. Sinalize amostra pequena. Não exponha telefones ou dados pessoais. Produza resumo de 2-4 frases; até 3 destaques; até 3 alertas; comparação atual x anterior de Nota geral, Atendimento, Ambiente, Produtos e Tempo de espera; temas recorrentes com contagem; produto específico apenas se realmente identificado; padrões de atendentes sem ataques; horários críticos somente com evidência; até 3 recomendações práticas; e uma prioridade da semana apenas se houver evidência. Retorne APENAS JSON válido sem markdown no formato {"generatedAt":"ISO","period":"texto","summary":"texto","status":"positivo|atencao|critico|sem_dados","confidenceNote":"texto","highlights":[{"title":"","description":"","evidence":"","type":"positivo"}],"alerts":[{"title":"","description":"","evidence":"","severity":"baixa|media|alta","type":"atencao"}],"evolution":[{"category":"","previous":4.2,"current":4.4,"trend":"melhorou|piorou|estavel"}],"themes":[{"theme":"","count":0,"sentiment":"positivo|negativo|neutro","summary":""}],"productInsights":[],"waiterInsights":[],"criticalHours":[],"recommendations":[],"weeklyPriority":{"problem":"","reason":"","action":""},"finalPhrase":""}. Use [] ou null quando não houver base. DADOS: ${JSON.stringify(payload)}`;
  const out=await ai.models.generateContent({model:process.env.GEMINI_MODEL||'gemini-2.5-flash',contents:prompt,config:{responseMimeType:'application/json',temperature:0.2}});const report=json(out.text||'');report.generatedAt=report.generatedAt||new Date().toISOString();report.period=report.period||label;return res.json({success:true,report});}catch(e:any){console.error('[AI report]',e);return res.status(500).json({error:e?.message||'Erro ao gerar relatório de IA.'})}});
  app.post('/api/ai/ask',async(req,res)=>{try{const db=getDb();if(!requirePro(db,res))return;const ai=client();if(!ai)return res.status(503).json({error:'Configure GEMINI_API_KEY no Render para ativar a IA.'});const q=String(req.body?.question||'').trim().slice(0,600);if(!q)return res.status(400).json({error:'Digite uma pergunta.'});const period=['today','7d','30d','all'].includes(String(req.body?.period))?String(req.body.period):'30d',x=select(db.reviews||[],period);const data={company:db.settings?.name||getCompanyId(),period:x.label,currentStats:stats(x.current),previousStats:stats(x.previous),reviews:compact(x.current),previousReviews:compact(x.previous)};const prompt=`Responda ao gestor usando SOMENTE os dados fornecidos. Não invente. Se não houver base, diga claramente. Não exponha dados pessoais. Seja direto, cite números e o período. Pergunta: ${q}. Dados: ${JSON.stringify(data)}`;const out=await ai.models.generateContent({model:process.env.GEMINI_MODEL||'gemini-2.5-flash',contents:prompt,config:{temperature:0.15}});return res.json({success:true,answer:String(out.text||'').trim()})}catch(e:any){console.error('[AI ask]',e);return res.status(500).json({error:e?.message||'Erro ao consultar a IA.'})}})
}
