import {before,after,beforeEach,test} from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {quote,addMonths,verifyWebhook,validatePayment,validCheckoutUrl} from '../billing-core';
import {initBillingSchema,prepareOrder,createRemote,applyPayment,handleBillingEvent,registerBillingRoutes} from '../billing';
const pg=new PGlite();let queue=Promise.resolve();
const pool={async connect(){const prev=queue;let release!:()=>void;queue=new Promise<void>(r=>release=r);await prev;return{query:(sql:string,args?:any[])=>pg.query(sql,args),release};},async query(sql:string,args?:any[]){const c=await this.connect();try{return await c.query(sql,args);}finally{c.release();}}};
const prices={basic:49.9,pro:99.9,premium:149.9};const cfg={collector:'1234',live:false};
const input={plan:'pro',cycle:'monthly',method:'pix',email:'owner@example.com'};
const paidAt=new Date();const stamp=new Date();
async function order(data:any={}) {return prepareOrder(pool,'a',{...input,...data},prices,20,'https://example.com');}
function payment(o:any,changes:any={}){return {id:'1001',collector_id:'1234',live_mode:false,currency_id:'BRL',transaction_amount:o.amount/100,external_reference:o.id,payment_method_id:'pix',status:'approved',date_approved:paidAt.toISOString(),date_created:stamp.toISOString(),date_last_updated:stamp.toISOString(),...changes};}
async function company(){return (await pool.query("SELECT * FROM avaliacao_empresas WHERE empresa_id='a'")).rows[0] as any;}
before(async()=>{await pool.query(`CREATE TABLE avaliacao_empresas(empresa_id TEXT PRIMARY KEY,nome TEXT,plano TEXT,ativo BOOLEAN DEFAULT TRUE,status_assinatura TEXT DEFAULT 'trial',vencimento_em TIMESTAMPTZ,atualizado_em TIMESTAMPTZ)`);await pool.query(`CREATE TABLE avaliacao_plataforma_config(id INTEGER PRIMARY KEY,dados JSONB,atualizado_em TIMESTAMPTZ);`);await initBillingSchema(pool);process.env.MP_ACCESS_TOKEN='mock';process.env.MP_WEBHOOK_SECRET='test-secret';process.env.MP_COLLECTOR_ID='1234';process.env.MP_LIVE_MODE='false';process.env.PUBLIC_APP_URL='https://example.com';});
beforeEach(async()=>{await pool.query('TRUNCATE avaliacao_billing_events,avaliacao_empresas CASCADE');for(const id of ['a','b'])await pool.query('INSERT INTO avaliacao_empresas(empresa_id,nome,plano)VALUES($1,$1,$2)',[id,'pro']);});
after(async()=>pg.close());
test('preços em centavos e desconto anual calculados exclusivamente no servidor',()=>{assert.deepEqual(quote(prices,'pro','annual',20),{amount:95904,months:12});assert.equal(quote(prices,'pro','monthly',20).amount,9990);assert.throws(()=>quote(prices,'unknown','annual',20));assert.throws(()=>quote(prices,'pro','annual',100));assert.throws(()=>quote({pro:0},'pro','monthly',0));});
test('calendário respeita fevereiro, fim do mês e ano bissexto',()=>{assert.equal(addMonths(new Date('2026-01-31T12:00:00Z'),1).toISOString(),'2026-02-28T12:00:00.000Z');assert.equal(addMonths(new Date('2024-02-29T12:00:00Z'),12).toISOString(),'2025-02-28T12:00:00.000Z');});
test('webhook rejeita assinatura falsa, timestamp vencido e ID alterado',()=>{const ts=String(Math.floor(Date.now()/1000));const v=crypto.createHmac('sha256','secret').update(`id:abc123;request-id:req-1;ts:${ts};`).digest('hex');assert.equal(verifyWebhook('secret','ABC123','req-1',`ts=${ts},v1=${v}`),true);assert.equal(verifyWebhook('secret','abc124','req-1',`ts=${ts},v1=${v}`),false);assert.equal(verifyWebhook('secret','abc123','req-1',`ts=${ts},v1=${v}`,Date.now()+700000),false);assert.equal(verifyWebhook('','abc123','req-1',`ts=${ts},v1=${v}`),false);});
test('checkout rejeita URLs externas e javascript',()=>{assert.equal(validCheckoutUrl('https://www.mercadopago.com.br/subscriptions/checkout?id=abc')?.startsWith('https:'),true);for(const u of ['javascript:alert(1)','https://mercadopago.com.br.evil.example','http://www.mercadopago.com.br'])assert.equal(validCheckoutUrl(u),null);});
test('tentativas concorrentes reutilizam uma única cobrança por empresa',async()=>{const [a,b]=await Promise.all([order(),order()]);assert.equal(a.id,b.id);await assert.rejects(order({method:'card'}));assert.equal((await pool.query('SELECT * FROM avaliacao_billing_orders')).rows.length,1);});
test('cliente não pode alterar valor; outra empresa tem cobrança independente',async()=>{const a=await order({amount:1});const b=await prepareOrder(pool,'b',input,prices,20,'https://example.com');assert.equal(a.amount,9990);assert.notEqual(a.id,b.id);});
test('suspensão administrativa impede contratação e plano pago não troca antes do prazo',async()=>{await pool.query("UPDATE avaliacao_empresas SET status_assinatura='suspended' WHERE empresa_id='a'");await assert.rejects(order());await pool.query("UPDATE avaliacao_empresas SET status_assinatura='active',vencimento_em=NOW()+INTERVAL '1 day' WHERE empresa_id='a'");await assert.rejects(order({plan:'premium'}));});
test('Pix usa a mesma chave após perda de resposta; cartão não cria segunda assinatura incerta',async()=>{const o=await order();let keys:string[]=[];await assert.rejects(createRemote(pool,o,async(_p,_m,_b,k)=>{keys.push(k!);throw Error('timeout');}));await createRemote(pool,o,async(_p,_m,_b,k)=>{keys.push(k!);return{id:1001,status:'pending'};});assert.equal(keys[0],keys[1]);await pool.query("UPDATE avaliacao_billing_orders SET status='cancelled'");const card=await order({method:'card'});let calls=0;const timeout=async()=>{calls++;throw Error('timeout');};await assert.rejects(createRemote(pool,card,timeout));await createRemote(pool,card,timeout);assert.equal(calls,1);});
test('criação e pendência não liberam acesso',async()=>{const o=await order();await createRemote(pool,o,async()=>({id:1001,status:'pending'}));await applyPayment(pool,o.id,payment(o,{status:'pending',date_approved:null}),cfg);assert.equal((await company()).vencimento_em,null);});
test('pagamento aprovado renova uma única vez mesmo com notificações concorrentes',async()=>{const o=await order();await Promise.all([applyPayment(pool,o.id,payment(o),cfg),applyPayment(pool,o.id,payment(o),cfg)]);assert.equal(new Date((await company()).vencimento_em).toISOString(),addMonths(paidAt,1).toISOString());assert.equal((await pool.query('SELECT * FROM avaliacao_billing_payments')).rows.length,1);});
test('anual concede doze meses e preserva dias restantes',async()=>{const end=new Date(Date.now()+7*86400000);await pool.query('UPDATE avaliacao_empresas SET vencimento_em=$1 WHERE empresa_id=$2',[end,'a']);const o=await order({cycle:'annual'});await applyPayment(pool,o.id,payment(o),cfg);assert.equal(new Date((await company()).vencimento_em).toISOString(),addMonths(end,12).toISOString());});
test('valor, moeda, conta recebedora, ambiente e referência divergentes não liberam acesso',async()=>{const o=await order();for(const change of [{transaction_amount:1},{currency_id:'USD'},{collector_id:'other'},{live_mode:true},{external_reference:'other'},{payment_method_id:'credit_card'}])await assert.rejects(applyPayment(pool,o.id,payment(o,change),cfg));assert.equal((await company()).vencimento_em,null);});
test('cartão exige vínculo confirmado com a assinatura e cada parcela só renova uma vez',async()=>{const o=await order({method:'card'});await pool.query("UPDATE avaliacao_billing_orders SET remote_id='sub1',status='authorized' WHERE id=$1",[o.id]);await assert.rejects(applyPayment(pool,o.id,payment(o),cfg));await applyPayment(pool,o.id,payment(o),cfg,'sub1');await applyPayment(pool,o.id,payment(o,{id:'1002'}),cfg,'sub1');assert.equal(new Date((await company()).vencimento_em).toISOString(),addMonths(addMonths(paidAt,1),1).toISOString());});
test('estorno suspende período concedido e aprovação atrasada não desfaz a suspensão',async()=>{const o=await order();await applyPayment(pool,o.id,payment(o),cfg);await applyPayment(pool,o.id,payment(o,{status:'refunded',transaction_amount_refunded:o.amount/100,date_last_updated:new Date(stamp.getTime()+1000).toISOString()}),cfg);await applyPayment(pool,o.id,payment(o),cfg);assert.equal((await company()).status_assinatura,'suspended');});
test('pagamento recebido durante suspensão não remove bloqueio administrativo',async()=>{const o=await order();await pool.query("UPDATE avaliacao_empresas SET status_assinatura='suspended' WHERE empresa_id='a'");await applyPayment(pool,o.id,payment(o),cfg);assert.equal((await company()).status_assinatura,'suspended');});
test('notificação consulta API do provedor em vez de confiar no corpo recebido',async()=>{const o=await order();let path='';await handleBillingEvent(pool,'payment','1001',async p=>{path=p;return payment(o);});assert.equal(path,'/v1/payments/1001');assert.ok((await company()).vencimento_em);});
test('falha ao atualizar empresa reverte também registro do pagamento',async()=>{const o=await order();const broken={connect:async()=>{const c=await pool.connect();return {...c,query:async(sql:string,args:any[])=>{if(sql.startsWith('UPDATE avaliacao_empresas'))throw Error('disk failure');return c.query(sql,args);}};}};await assert.rejects(applyPayment(broken,o.id,payment(o),cfg));assert.equal((await pool.query('SELECT * FROM avaliacao_billing_payments')).rows.length,0);assert.equal((await company()).vencimento_em,null);});
test('rotas financeiras exigem proprietário e não expõem cobrança de outra empresa',async()=>{const routes:Record<string,any[]>={};const app:any={get:(p:string,...h:any[])=>routes['GET '+p]=h,post:(p:string,...h:any[])=>routes['POST '+p]=h,put:(p:string,...h:any[])=>routes['PUT '+p]=h};const guard=()=>{},admin=()=>{};registerBillingRoutes(app,pool,guard,admin,()=> 'b',async()=>prices);for(const [key,handlers]of Object.entries(routes)){if(key==='POST /api/billing/webhook')continue;assert.equal(handlers[0],key.includes('/admin/')?admin:guard);}const o=await order();await assert.rejects(routes['POST /api/billing/orders/:id/sync'][1]({params:{id:o.id}},{}));});
test('autorização de assinatura não libera acesso e notificação antiga não reabre cancelamento',async()=>{const o=await order({method:'card'});const subscription={id:'sub1',external_reference:o.id,collector_id:'1234',auto_recurring:{currency_id:'BRL',transaction_amount:o.amount/100,frequency:1,frequency_type:'months'},status:'authorized',last_modified:stamp.toISOString()};await handleBillingEvent(pool,'subscription_preapproval','sub1',async()=>subscription);assert.equal((await company()).vencimento_em,null);await handleBillingEvent(pool,'subscription_preapproval','sub1',async()=>({...subscription,status:'cancelled',last_modified:new Date(stamp.getTime()+1000).toISOString()}));await handleBillingEvent(pool,'subscription_preapproval','sub1',async()=>subscription);assert.equal((await pool.query('SELECT status FROM avaliacao_billing_orders WHERE id=$1',[o.id])).rows[0].status,'cancelled');});
test('pagamento de assinatura é confirmado pela fatura, assinatura e pagamento na API',async()=>{const o=await order({method:'card'});const paths:string[]=[];await handleBillingEvent(pool,'subscription_authorized_payment','invoice1',async path=>{paths.push(path);if(path==='/authorized_payments/invoice1')return{preapproval_id:'sub1',payment:{id:1001}};if(path==='/preapproval/sub1')return{id:'sub1',external_reference:o.id,collector_id:'1234',auto_recurring:{currency_id:'BRL',transaction_amount:o.amount/100,frequency:1,frequency_type:'months'},status:'authorized',last_modified:stamp.toISOString()};if(path==='/v1/payments/1001')return payment(o,{external_reference:null,payment_method_id:'visa'});throw Error('unexpected API');});assert.equal(paths.length,3);assert.ok((await company()).vencimento_em);});
test('webhook só confirma recebimento após persistir e rejeita evento adulterado',async()=>{const routes:Record<string,any[]>={};const app:any={get:()=>{},put:()=>{},post:(p:string,...h:any[])=>routes[p]=h};registerBillingRoutes(app,pool,()=>{},()=>{},()=> 'a',async()=>prices);const handler=routes['/api/billing/webhook'][0];const ts=String(Math.floor(Date.now()/1000));const sign=crypto.createHmac('sha256','test-secret').update(`id:1001;request-id:req-1;ts:${ts};`).digest('hex');const req={query:{'data.id':'1001'},body:{type:'payment',data:{id:'1001'}},header:(k:string)=>k==='x-request-id'?'req-1':`ts=${ts},v1=${sign}`};let status=0;const res:any={status:(s:number)=>{status=s;return res;},json:()=>{},sendStatus:(s:number)=>{status=s;}};await handler(req,res);assert.equal(status,200);assert.equal((await pool.query('SELECT * FROM avaliacao_billing_events')).rows.length,1);await handler(req,res);assert.equal((await pool.query('SELECT * FROM avaliacao_billing_events')).rows.length,1);await handler({...req,body:{type:'payment',data:{id:'1002'}}},res);assert.equal(status,400);const failApp:any={get:()=>{},put:()=>{},post:(p:string,...h:any[])=>routes[p]=h};registerBillingRoutes(failApp,{query:async()=>{throw Error('database offline');}},()=>{},()=>{},()=> 'a',async()=>prices);status=0;await assert.rejects(routes['/api/billing/webhook'][0](req,res));assert.equal(status,0);});
