import {useEffect,useState} from 'react';
export function BillingAdmin({token}:{token:string}){
 const[data,setData]=useState<any>(null),[discount,setDiscount]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const request=async(method='GET',body?:any)=>{const r=await fetch('/api/admin/billing',{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Erro ao consultar pagamentos.');return d;};
 const load=async()=>{const d=await request();setData(d);setDiscount(d.annualDiscountPercent);};
 useEffect(()=>{load().catch(e=>setError(e.message));},[token]);
 return <section className="bg-white rounded-2xl border border-stone-200 p-5 space-y-4"><h2 className="font-black text-xl">Pagamentos — Mercado Pago</h2>{error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-green-700">{message}</p>}
 <p className="text-sm">{data?.configured?'Credenciais configuradas.':'Configure MP_ACCESS_TOKEN, MP_COLLECTOR_ID, MP_WEBHOOK_SECRET e PUBLIC_APP_URL no servidor.'}</p>
 {data?.webhookUrl&&<p className="text-sm break-all">URL para notificações: <code>{data.webhookUrl}</code></p>}
 <form className="flex gap-3 items-end flex-wrap" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request('PUT',{annualDiscountPercent:discount});await load();setMessage('Desconto salvo para novas contratações.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label className="text-sm font-bold">Desconto anual (%)<input className="block border rounded-xl p-2 mt-1" type="number" min={0} max={90} step="0.01" required value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><button className="bg-rose-700 text-white rounded-xl px-4 py-2 font-bold disabled:opacity-50" disabled={busy}>Salvar desconto</button><button type="button" className="border rounded-xl px-4 py-2" onClick={()=>load().catch(e=>setError(e.message))}>Atualizar</button></form>
 <p className="text-xs text-stone-500">Anual = preço mensal × 12 − desconto. Os preços dos planos acima passam a valer nas novas cobranças. Assinaturas já contratadas mantêm o valor combinado. O desconto inicia em 0% até você defini-lo.</p>
 <p className="text-sm">Notificações aguardando processamento: {data?.pendingEvents??'—'}</p>
 <div className="overflow-x-auto"><h3 className="font-bold mb-2">Últimos pagamentos</h3><table className="w-full text-left text-sm"><thead><tr><th>Empresa</th><th>Pagamento</th><th>Valor</th><th>Status</th></tr></thead><tbody>{data?.payments?.map((p:any)=><tr key={p.id} className="border-t"><td className="py-2">{p.nome}</td><td>{p.id}</td><td>{(p.amount/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td>{p.status}{p.refunded>0?' · com devolução':''}</td></tr>)}</tbody></table></div>
 <details><summary className="cursor-pointer font-bold">Últimas contratações e cobranças</summary><div className="overflow-x-auto"><table className="text-sm w-full text-left"><thead><tr><th>Empresa</th><th>Plano / período</th><th>Meio</th><th>Status</th></tr></thead><tbody>{data?.orders?.map((o:any)=><tr className="border-t" key={o.id}><td className="py-2">{o.nome}</td><td>{o.plan} / {o.cycle}</td><td>{o.method}</td><td>{o.status}<small className="block">{o.id}</small></td></tr>)}</tbody></table></div></details></section>;
}
