import {useEffect,useState,type FormEvent} from 'react';
import QRCode from 'qrcode';
import {tenantFetch,apiManagerLogin} from '../lib/api';
import {getCompanyId,tenantKey} from '../lib/tenant';
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
const date=(v:any)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const names:Record<string,string>={basic:'Básico',pro:'Pro',premium:'Premium'};
const states:Record<string,string>={creating:'Preparando',uncertain:'Aguardando confirmação',pending:'Aguardando pagamento',authorized:'Renovação automática ativa',paused:'Renovação pausada',cancelled:'Cancelado',approved:'Pago',rejected:'Recusado',refunded:'Reembolsado',charged_back:'Contestado',in_process:'Em processamento'};
const field='w-full rounded-xl border border-stone-300 p-3 bg-white';
const button='rounded-xl bg-rose-700 text-white px-5 py-3 font-bold disabled:opacity-50';
function PixCode({value}:{value:string}){const[image,setImage]=useState('');const[copied,setCopied]=useState(false);useEffect(()=>{let alive=true;QRCode.toDataURL(value,{width:240,margin:2}).then(x=>{if(alive)setImage(x);});return()=>{alive=false;};},[value]);return <div className="space-y-3">{image&&<img src={image} width={240} height={240} alt="QR Code para pagar com Pix"/>}<label className="block text-sm">Pix Copia e Cola<textarea readOnly value={value} className={field}/></label><button className={button} onClick={()=>navigator.clipboard.writeText(value).then(()=>setCopied(true)).catch(()=>setCopied(false))}>{copied?'Copiado':'Copiar código Pix'}</button></div>;}
export function BillingPage(){
  const[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[needsLogin,setNeedsLogin]=useState(false);
  const[login,setLogin]=useState(''),[password,setPassword]=useState(''),[email,setEmail]=useState(''),[plan,setPlan]=useState('pro'),[cycle,setCycle]=useState('monthly'),[method,setMethod]=useState('pix');
  const[accepted,setAccepted]=useState(false),[notice,setNotice]=useState('');
  const load=async()=>{const r=await tenantFetch('/api/billing',{cache:'no-store'});const d=await r.json();if(r.status===401){setNeedsLogin(true);return;}if(!r.ok)throw Error(d.error||'Não foi possível carregar a assinatura.');setNeedsLogin(false);setData(d);};
  useEffect(()=>{load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),15000);return()=>clearInterval(t);},[]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e:any){setError(e.message);await load().catch(()=>{});}finally{setBusy(false);}};
  const post=async(url:string,body:any={})=>{const r=await tenantFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Operação não confirmada.');return d;};
  const signIn=(e:FormEvent)=>{e.preventDefault();void run(async()=>{const r=await apiManagerLogin(login,password,true);if(!r.success)throw Error(r.error);sessionStorage.setItem(tenantKey('restaurant_manager_auth'),'true');sessionStorage.setItem(tenantKey('restaurant_manager_role'),r.role||'manager');sessionStorage.setItem(tenantKey('restaurant_manager_access'),r.accessLevel||'owner');setPassword('');});};
  useEffect(()=>{if(data?.company?.plano)setPlan(data.company.plano);},[data?.company?.plano]);
  useEffect(()=>{if(data?.company?.email_cobranca&&!email)setEmail(data.company.email_cobranca);},[data?.company?.email_cobranca]);
  const offer=data?.offers?.find((x:any)=>x.plan===plan);const amount=offer?.[cycle]||0;
  const open=data?.orders?.find((o:any)=>['creating','uncertain','pending','authorized','paused','in_process'].includes(o.status));
  const company=data?.company;const suspended=company&&(!company.ativo||company.status_assinatura==='suspended');
  return <main className="min-h-screen bg-stone-100 p-4 sm:p-8 text-stone-900"><div className="max-w-4xl mx-auto space-y-6">
    <header className="flex justify-between items-center gap-3"><div><p className="font-bold text-rose-700">Avalia e Ganha</p><h1 className="text-3xl font-black">Minha assinatura</h1><p className="text-stone-600">{company?.nome||getCompanyId()}</p></div><a className="underline" href={`/gerencia?empresa=${encodeURIComponent(getCompanyId())}`}>Voltar ao painel</a></header>
    {error&&<p role="alert" className="p-4 rounded-xl bg-red-50 text-red-800">{error}</p>}{notice&&<p role="status" className="p-4 bg-green-50 text-green-800 rounded-xl">{notice}</p>}
    {needsLogin?<form onSubmit={signIn} className="p-6 bg-white rounded-2xl space-y-4"><h2 className="font-bold">Entre com o acesso do proprietário</h2><p className="text-sm">Você pode renovar ou cancelar a assinatura mesmo com o acesso vencido.</p><input className={field} aria-label="Login" placeholder="Login" autoComplete="username" value={login} onChange={e=>setLogin(e.target.value)} required/><input className={field} aria-label="Senha" placeholder="Senha" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className={button} disabled={busy}>Entrar</button></form>:data&&<>
    <section className="p-6 bg-white rounded-2xl"><h2 className="font-bold">Plano atual: {names[company?.plano]}</h2><p>Acesso até: {date(company?.vencimento_em)}</p>{suspended&&<p className="text-red-700">A empresa está suspensa. Entre em contato com o suporte. Você ainda pode cancelar a renovação abaixo.</p>}</section>
    {!data.configured&&<p className="p-4 bg-amber-50 rounded-xl">O administrador está configurando os pagamentos. A contratação estará disponível em breve.</p>}
    {open?<section className="p-6 bg-white rounded-2xl space-y-4"><h2 className="text-xl font-bold">{states[open.status]||open.status}</h2><p>{names[open.plan]} · {open.cycle==='annual'?'Anual':'Mensal'} · {money(open.amount)} · {open.method==='pix'?'Pix':'Cartão / Mercado Pago'}</p>
      {open.method==='pix'&&open.pixCode&&(!open.pixExpiresAt||new Date(open.pixExpiresAt)>new Date())&&<><PixCode value={open.pixCode}/><p className="text-sm">QR Code válido até {date(open.pixExpiresAt)}. Confira o valor e o recebedor no seu banco.</p></>}
      {open.method==='pix'&&open.pixExpiresAt&&new Date(open.pixExpiresAt)<=new Date()&&<p className="text-amber-800">O prazo deste QR Code terminou. Atualize o status e, se necessário, cancele a cobrança pendente para gerar outra.</p>}
      {open.method==='card'&&open.checkoutUrl&&open.status==='pending'&&<a className={`${button} inline-block`} href={open.checkoutUrl} target="_blank" rel="noopener noreferrer">Continuar no Mercado Pago</a>}
      <p className="text-sm text-stone-600">O acesso só é renovado após a confirmação do pagamento. Autorizar o cartão ou voltar do checkout não confirma a cobrança.</p>
      <div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>run(async()=>{await post(`/api/billing/orders/${open.id}/sync`);setNotice('Status consultado.');})}>Atualizar status</button><button className="rounded-xl border px-4 py-3" disabled={busy} onClick={()=>{if(window.confirm(open.method==='card'?'Cancelar as próximas cobranças? O período já pago será mantido.':'Cancelar este Pix pendente?'))void run(async()=>{await post(`/api/billing/orders/${open.id}/cancel`);setNotice('Cancelamento confirmado. O período já pago foi mantido.');});}}>{open.method==='card'?'Cancelar renovação':'Cancelar cobrança'}</button></div></section>:
    <form onSubmit={e=>{e.preventDefault();void run(async()=>{await post('/api/billing/orders',{plan,cycle,method,email});setNotice(method==='pix'?'Cobrança Pix criada.':'Assinatura criada. Continue no Mercado Pago para autorizar.');});}} className="p-6 bg-white rounded-2xl space-y-5">
      <h2 className="text-xl font-bold">Contratar ou renovar</h2><div className="grid sm:grid-cols-3 gap-4"><label>Plano<select className={field} value={plan} onChange={e=>setPlan(e.target.value)}>{data.offers.map((p:any)=><option key={p.plan} value={p.plan}>{names[p.plan]}</option>)}</select></label><label>Período<select className={field} value={cycle} onChange={e=>{setCycle(e.target.value);setAccepted(false);}}><option value="monthly">Mensal</option><option value="annual">Anual{data.annualDiscountPercent>0?` · ${data.annualDiscountPercent}% de desconto`:''}</option></select></label><label>Pagamento<select className={field} value={method} onChange={e=>{setMethod(e.target.value);setAccepted(false);}}><option value="pix">Pix</option><option value="card">Cartão recorrente</option></select></label></div>
      <label className="block">E-mail do pagador<input className={field} type="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254}/><span className="block mt-1 text-xs text-stone-500">Usamos os dados cadastrados da empresa (CPF/CNPJ e e-mail) para identificar a cobrança.</span></label>
      <div className="p-4 rounded-xl bg-rose-50"><strong className="text-3xl">{money(amount)}</strong><p>{cycle==='annual'?'Total para 12 meses, em uma cobrança.':'Valor de um mês.'}</p>{cycle==='annual'&&data.annualDiscountPercent>0&&<p>Economia de {money(offer.monthly*12-amount)} por ano.</p>}<p className="mt-2 text-sm">{method==='pix'?'Pix com confirmação automática. A cada renovação, você gera e paga um novo QR Code.':`Renovação automática ${cycle==='annual'?'a cada 12 meses':'mensal'}. Você autoriza a cobrança no Mercado Pago e pode cancelar as próximas cobranças nesta página.`}</p></div>
      <label className="flex gap-3 items-start"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required/><span className="text-sm">Concordo com o valor, o período e as condições de renovação acima.</span></label><button className={button} disabled={busy||!accepted||!amount||!data.configured||suspended}>{busy?'Aguarde…':method==='pix'?'Gerar Pix':'Assinar com cartão'}</button>
      <p className="text-xs text-stone-500">Mudanças de plano durante um período já pago devem ser solicitadas ao suporte. Ao contratar cartão antes do vencimento, a primeira cobrança é programada para o fim do acesso atual.</p>
    </form>}
    <section className="p-6 bg-white rounded-2xl overflow-x-auto"><h2 className="font-bold text-xl mb-4">Histórico de pagamentos</h2><table className="w-full text-sm text-left"><thead><tr><th className="p-2">Data</th><th>Plano</th><th>Valor</th><th>Status</th><th>Acesso até</th></tr></thead><tbody>{data.payments.map((p:any)=><tr key={p.id} className="border-t"><td className="p-2">{date(p.paid_at)}</td><td>{names[p.plan]} · {p.cycle==='annual'?'Anual':'Mensal'}</td><td>{money(p.amount)}</td><td>{states[p.status]||p.status}{p.refunded>0?` · devolvido ${money(p.refunded)}`:''}</td><td>{date(p.granted_until)}</td></tr>)}</tbody></table>{!data.payments.length&&<p className="text-stone-500 mt-3">Nenhum pagamento confirmado ainda.</p>}</section>
    </>}
  </div></main>;
}
